In [1]:
import pandas as pd

from pathlib import Path

import sys
sys.path.append("../../src")
from weights import get_random_w_mat

In [2]:
decoy_file = "../data/266_decoys/rand1000.csv"
decoy_df = pd.read_csv(decoy_file, index_col=0)
decoy_df.head()

,pdb,ff,rmsd,w_0_0,w_0_1,w_1_0,w_1_1
0,/wynton/group/sali/mhancock/xray/sample_bench/...,789.988948,0.214138,0.9,0.1,0.1,0.9
1,/wynton/group/sali/mhancock/xray/sample_bench/...,889.430417,0.108996,0.9,0.1,0.1,0.9
2,/wynton/group/sali/mhancock/xray/sample_bench/...,587.807530,0.186456,0.9,0.1,0.1,0.9
3,/wynton/group/sali/mhancock/xray/sample_bench/...,4687.550984,0.056656,0.9,0.1,0.1,0.9
4,/wynton/group/sali/mhancock/xray/sample_bench/...,3015.672514,0.067009,0.9,0.1,0.1,0.9

In [3]:
for i in range(len(decoy_df)):
    w_mat = get_random_w_mat(2, 2)

    for state in range(2):
        for cond in range(2):
            decoy_df.loc[i, "w_{}_{}".format(state, cond)] = w_mat[state, cond]

In [4]:
decoy_df.head()

,pdb,ff,rmsd,w_0_0,w_0_1,w_1_0,w_1_1
0,/wynton/group/sali/mhancock/xray/sample_bench/...,789.988948,0.214138,0.437469,0.615200,0.562531,0.384800
1,/wynton/group/sali/mhancock/xray/sample_bench/...,889.430417,0.108996,0.865468,0.180990,0.134532,0.819010
2,/wynton/group/sali/mhancock/xray/sample_bench/...,587.807530,0.186456,0.606549,0.968560,0.393451,0.031440
3,/wynton/group/sali/mhancock/xray/sample_bench/...,4687.550984,0.056656,0.984052,0.395749,0.015948,0.604251
4,/wynton/group/sali/mhancock/xray/sample_bench/...,3015.672514,0.067009,0.771339,0.401298,0.228661,0.598702

In [5]:
decoy_df.to_csv(decoy_file)