In [2]:
from pathlib import Path
import pandas as pd

In [12]:
cif_df = pd.read_csv(Path(Path.home(), "Documents/xray/dev/29_synthetic_native_3/data/cifs/csvs/7mhf_30.csv"), index_col=0)
job_ids = cif_df.index
Ns = [1, 2]
w_xrays = [2**i for i in range(-5,6)]
w_xrays.sort()

In [17]:
input_df = pd.DataFrame()

for N in Ns:
    for j in range(20):
        cif_0 = cif_df.loc[j, "cif_0"]
        cif_1 = cif_df.loc[j, "cif_1"]
        ref_0 = cif_df.loc[j, "ref_0"]
        ref_1 = cif_df.loc[j, "ref_1"]
        w_0_0 = cif_df.loc[j, "w_0_0"]
        w_1_0 = cif_df.loc[j, "w_1_0"]
        w_0_1 = cif_df.loc[j, "w_0_1"]
        w_1_1 = cif_df.loc[j, "w_1_1"]

        for w_xray in w_xrays:
            input_id = len(input_df)

            input_df.loc[input_id, "N"] = N
            if j % 2 == 0:
                input_df.loc[input_id, "J"] = 1
            else:
                input_df.loc[input_id, "J"] = 2

            input_df.loc[input_id, "cif_0"] = cif_0
            input_df.loc[input_id, "cif_1"] = cif_1
            input_df.loc[input_id, "ref_0"] = ref_0
            input_df.loc[input_id, "ref_1"] = ref_1
            input_df.loc[input_id, "w_0_0"] = w_0_0
            input_df.loc[input_id, "w_1_0"] = w_1_0
            input_df.loc[input_id, "w_0_1"] = w_0_1
            input_df.loc[input_id, "w_1_1"] = w_1_1

            input_df.loc[input_id, "w_xray"] = w_xray

input_df["sample_sched_str"] = "step3000,T300,dofA,pdb1,w1,res2"
input_df["start_pdb_file"] = "/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhf_refine.pdb"

# input_df["N"] = input_df["N"].astype(int)

input_df.head()

/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_47990/936228187.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/dev/29_synthetic_native_3/data/cifs/7mhf_30/0/1.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_1"] = cif_1
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_47990/936228187.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/dev/29_synthetic_native_3/data/pdbs/7mhf_30/0.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_1"] = ref_1

,N,J,cif_0,cif_1,ref_0,ref_1,w_0_0,w_1_0,w_0_1,w_1_1,w_xray,sample_sched_str,start_pdb_file
0,1.0,1.0,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,0.510588,0.489412,NaN,NaN,0.03125,"step3000,T300,dofA,pdb1,w1,res2",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
1,1.0,1.0,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,0.510588,0.489412,NaN,NaN,0.06250,"step3000,T300,dofA,pdb1,w1,res2",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
2,1.0,1.0,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,0.510588,0.489412,NaN,NaN,0.12500,"step3000,T300,dofA,pdb1,w1,res2",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
3,1.0,1.0,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,0.510588,0.489412,NaN,NaN,0.25000,"step3000,T300,dofA,pdb1,w1,res2",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
4,1.0,1.0,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,/wynton/home/sali/mhancock/xray/dev/29_synthet...,NaN,0.510588,0.489412,NaN,NaN,0.50000,"step3000,T300,dofA,pdb1,w1,res2",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...

In [18]:
input_df.to_csv(Path(Path.home(), "Documents/xray/sample_bench/data/params/w_xray_bench.csv"))