In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
cif_df = pd.read_csv(Path(Path.home(), "Documents/xray/dev/35_cif_combos/data/7mhf.csv"), index_col=0)
cif_df.head()

,cif_0,ref_0,w_0_0,cif_1,ref_1,w_0_1,cif_2,ref_2,w_0_2,cif_3,ref_3,w_0_3,cif_4,ref_4,w_0_4,cif_5,ref_5,w_0_5
0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
cif_df.tail()

,cif_0,ref_0,w_0_0,cif_1,ref_1,w_0_1,cif_2,ref_2,w_0_2,cif_3,ref_3,w_0_3,cif_4,ref_4,w_0_4,cif_5,ref_5,w_0_5
58,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN
59,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN
60,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN
61,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,NaN
62,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0

In [4]:
w_xray_df = pd.read_csv(Path(Path.home(), "Documents/xray/sample_bench/data/7mhf/188_w_xray_exp_ref_10000/best_w_xray.csv"), index_col=0)
w_xray_df.head()

,N,J,w_xray,r_free,w_0_7mhf,ff,pdb,cif_0,w_0_7mhg,w_0_7mhh,...,w_14_7mhj,w_15_7mhj,w_8_7mhk,w_9_7mhk,w_10_7mhk,w_11_7mhk,w_12_7mhk,w_13_7mhk,w_14_7mhk,w_15_7mhk
0,1.0,1.0,0.50,0.318842,1.0,796.493888,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.50,0.299476,NaN,744.999730,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.25,0.307301,NaN,879.624454,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.50,0.281027,NaN,1062.629216,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.25,0.301182,NaN,465.271059,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
w_xray_df_tmp = w_xray_df.copy()
w_xray_df_tmp.fillna(0, inplace=True)
cif_df_tmp = cif_df.copy()
cif_df_tmp.fillna(0, inplace=True)

In [6]:
cif_cols = ["cif_{}".format(i) for i in range(6)]
ref_cols = ["ref_{}".format(i) for i in range(6)]

In [11]:
len(cif_df.loc[6, cif_cols].dropna())

2

In [17]:
input_df = pd.DataFrame()

input_id = 0
for N in [1, 2, 4, 8, 16]:
    for j in range(63):
        input_df.loc[input_id, "N"] = N
        input_df.loc[input_id, "J"] = len(cif_df.loc[j, cif_cols].dropna())

        for i in range(len(cif_cols)):
            input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
            input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]
            input_df.loc[input_id, "w_{}_{}".format(0, i)] = 1

        w_xray_row = w_xray_df.loc[(w_xray_df_tmp["cif_0"] == cif_df_tmp.loc[j, "cif_0"]) & (w_xray_df_tmp["cif_1"] == cif_df_tmp.loc[j, "cif_1"]) & (w_xray_df_tmp["cif_2"] == cif_df_tmp.loc[j, "cif_2"]) & (w_xray_df_tmp["cif_3"] == cif_df_tmp.loc[j, "cif_3"]) & (w_xray_df_tmp["cif_4"] == cif_df_tmp.loc[j, "cif_4"]) & (w_xray_df_tmp["cif_5"] == cif_df_tmp.loc[j, "cif_5"]) & (w_xray_df_tmp["N"] == N)]
        w_xray = w_xray_row["w_xray"].values[0]
        input_df.loc[input_id, "w_xray"] = w_xray

        input_id += 1

input_df["sample_sched_str"] = "step3000,T300,dofA,pdb1,w1,res0"
input_df["start_pdb_file"] = "/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhf_refine.pdb"

# input_df["N"] = input_df["N"].astype(int)

input_df.head()

/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/cifs/7mhf/7mhg.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhg.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/cifs/7mhf/7mhh.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhh.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/cifs/7mhf/7mhi.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhi.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/cifs/7mhf/7mhj.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhj.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/cifs/7mhf/7mhk.cif' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "cif_{}".format(i)] = cif_df.loc[j, "cif_{}".format(i)]
/var/folders/x2/ss4b83151c31mg5h31tlp3ym0000gn/T/ipykernel_3130/3922539546.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '/wynton/home/sali/mhancock/xray/data/pdbs/7mhf/7mhk.pdb' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_df.loc[input_id, "ref_{}".format(i)] = cif_df.loc[j, "ref_{}".format(i)]

,N,J,cif_0,ref_0,w_0_0,cif_1,ref_1,w_0_1,cif_2,ref_2,...,w_0_3,cif_4,ref_4,w_0_4,cif_5,ref_5,w_0_5,w_xray,sample_sched_str,start_pdb_file
0,1.0,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,0.50,"step3000,T300,dofA,pdb1,w1,res0",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
1,1.0,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,0.50,"step3000,T300,dofA,pdb1,w1,res0",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
2,1.0,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,0.25,"step3000,T300,dofA,pdb1,w1,res0",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
3,1.0,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,0.50,"step3000,T300,dofA,pdb1,w1,res0",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...
4,1.0,1.0,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...,1.0,NaN,NaN,1.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,0.25,"step3000,T300,dofA,pdb1,w1,res0",/wynton/home/sali/mhancock/xray/data/pdbs/7mhf...

In [18]:
input_df.to_csv(Path(Path.home(), "Documents/xray/sample_bench/data/params/exp.csv"))