In [21]:
import pandas as pd
from pathlib import Path

In [27]:
wxray_df = pd.read_csv(Path(Path.home(), "Documents/xray/sample_bench/data/7mhf/178_wxray/w_xray.csv"), index_col=0)

In [28]:
w_xrays = [0.03125, 0.0625, .125, .25, .5, 1, 2, 4, 8, 16, 32]
n_states = [1, 2, 4, 8, 16]

In [31]:
min_idx = wxray_df.groupby(['state_id', 'job_id'])['field'].idxmin()

# Use the indices to filter the rows from the original dataframe
best_wxray_df = wxray_df.loc[min_idx]
best_wxray_df['w_xray'] = best_wxray_df['w_xray_id'].map(lambda x: w_xrays[int(x)])
best_wxray_df["N"] = best_wxray_df['state_id'].map(lambda x: n_states[int(x)])

best_wxray_df.head()

,state_id,job_id,w_xray_id,field,r_free_7mhf,ff,pdb,r_free_7mhg,r_free_7mhh,r_free_7mhi,r_free_7mhj,r_free_7mhk,w_xray,N
4,0.0,0.0,4.0,0.315629,0.315629,1913.176838,/wynton/group/sali/mhancock/xray/sample_bench/...,NaN,NaN,NaN,NaN,NaN,0.50,1
15,0.0,1.0,4.0,0.297294,NaN,1797.773282,/wynton/group/sali/mhancock/xray/sample_bench/...,0.297294,NaN,NaN,NaN,NaN,0.50,1
25,0.0,2.0,3.0,0.308920,NaN,1863.190033,/wynton/group/sali/mhancock/xray/sample_bench/...,NaN,0.30892,NaN,NaN,NaN,0.25,1
37,0.0,3.0,4.0,0.290543,NaN,2268.725439,/wynton/group/sali/mhancock/xray/sample_bench/...,NaN,NaN,0.290543,NaN,NaN,0.50,1
47,0.0,4.0,3.0,0.298457,NaN,1844.595650,/wynton/group/sali/mhancock/xray/sample_bench/...,NaN,NaN,NaN,0.298457,NaN,0.25,1

In [32]:
best_wxray_df.tail()

,state_id,job_id,w_xray_id,field,r_free_7mhf,ff,pdb,r_free_7mhg,r_free_7mhh,r_free_7mhi,r_free_7mhj,r_free_7mhk,w_xray,N
3414,4.0,58.0,4.0,1.324532,0.333223,1.444661e+06,/wynton/group/sali/mhancock/xray/sample_bench/...,0.315586,0.217826,NaN,0.229622,0.228275,0.5,16
3425,4.0,59.0,4.0,1.337765,0.308391,1.530526e+06,/wynton/group/sali/mhancock/xray/sample_bench/...,0.306335,NaN,0.224491,0.264278,0.234269,0.5,16
3436,4.0,60.0,4.0,1.198342,0.363676,1.609768e+06,/wynton/group/sali/mhancock/xray/sample_bench/...,NaN,0.201369,0.195517,0.207073,0.230707,0.5,16
3447,4.0,61.0,4.0,1.193470,NaN,1.317338e+06,/wynton/group/sali/mhancock/xray/sample_bench/...,0.348575,0.216485,0.198532,0.197358,0.232520,0.5,16
3458,4.0,62.0,4.0,1.444052,0.341266,1.515557e+06,/wynton/group/sali/mhancock/xray/sample_bench/...,0.305242,0.187461,0.200758,0.200760,0.208565,0.5,16

In [33]:
best_wxray_df.to_csv(Path(Path.home(), "Documents/xray/sample_bench/data/7mhf/178_wxray/best_wxray.csv"))