In [21]:
import pandas as pd
from pathlib import Path

In [22]:
exp_name = "188_w_xray_exp_ref_10000"
w_xray_df = pd.read_csv(Path(Path.home(), "Documents/xray/sample_bench/data/7mhf/{}/w_xray.csv".format(exp_name)), index_col=0)
w_xray_df.head()

w_xray_filt_df = w_xray_df.loc[w_xray_df["ff"] < 200000]
# w_xray_filt_df = w_xray_df
w_xray_filt_df.head()

,N,J,w_xray,r_free,w_0_7mhf,ff,pdb,cif_0,w_0_7mhg,w_0_7mhh,...,w_14_7mhj,w_15_7mhj,w_8_7mhk,w_9_7mhk,w_10_7mhk,w_11_7mhk,w_12_7mhk,w_13_7mhk,w_14_7mhk,w_15_7mhk
0,1.0,1.0,0.03125,0.468174,1.0,1174.639102,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.06250,0.432173,1.0,620.769686,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.12500,0.368398,1.0,776.746700,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.25000,0.325865,1.0,328.359905,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.50000,0.318842,1.0,796.493888,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# wxray_filt_df = wxray_df

match_cols = ["N", "J"]
cif_cols = [col for col in w_xray_filt_df.columns if "cif" in col]
match_cols.extend(cif_cols)
print(match_cols)
# min_idx = w_xray_filt_df.groupby(match_cols)['r_free'].idxmin()
w_xray_filt_df_tmp = w_xray_filt_df.fillna('nan')
min_idx = w_xray_filt_df_tmp.groupby(match_cols)["r_free"].idxmin()

best_w_xray_df = w_xray_filt_df.loc[min_idx]
# best_wxray_df['w_xray'] = best_wxray_df['w_xray_id'].map(lambda x: w_xrays[int(x)])
# best_wxray_df["N"] = best_wxray_df['state_id'].map(lambda x: n_states[int(x)])

print(len(best_w_xray_df))
best_w_xray_df.reset_index(drop=True, inplace=True)
best_w_xray_df.head()

['N', 'J', 'cif_0', 'cif_1', 'cif_2', 'cif_3', 'cif_4', 'cif_5']
315

,N,J,w_xray,r_free,w_0_7mhf,ff,pdb,cif_0,w_0_7mhg,w_0_7mhh,...,w_14_7mhj,w_15_7mhj,w_8_7mhk,w_9_7mhk,w_10_7mhk,w_11_7mhk,w_12_7mhk,w_13_7mhk,w_14_7mhk,w_15_7mhk
0,1.0,1.0,0.50,0.318842,1.0,796.493888,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.50,0.299476,NaN,744.999730,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.25,0.307301,NaN,879.624454,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.50,0.281027,NaN,1062.629216,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.25,0.301182,NaN,465.271059,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
best_w_xray_df.tail()

,N,J,w_xray,r_free,w_0_7mhf,ff,pdb,cif_0,w_0_7mhg,w_0_7mhh,...,w_14_7mhj,w_15_7mhj,w_8_7mhk,w_9_7mhk,w_10_7mhk,w_11_7mhk,w_12_7mhk,w_13_7mhk,w_14_7mhk,w_15_7mhk
310,16.0,5.0,0.25,0.312362,0.102741,46621.506045,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,16.0,5.0,0.50,0.311123,0.100114,86813.582749,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,16.0,5.0,0.25,0.331649,0.098302,49650.988001,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,16.0,5.0,0.50,0.305511,NaN,95105.861093,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,0.088412,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,16.0,6.0,0.50,0.320788,0.125746,112107.997968,/wynton/group/sali/mhancock/xray/sample_bench/...,/wynton/home/sali/mhancock/xray/data/cifs/7mhf...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
best_w_xray_df.to_csv(Path(Path.home(), "Documents/xray/sample_bench/data/7mhf/{}/best_w_xray.csv".format(exp_name)))